version: "3.9"
services:
  coordinator_db:
    container_name: coordinator_db
    image: postgres
    restart: always
    volumes:
      - ./coordinator/db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: 'revault'
      POSTGRES_PASSWORD: 'revault'
      POSTGRES_DB: 'coordinator_db'

  coordinatord:
    image: coordinatord
    container_name: coordinatord
    entrypoint: ["./entrypoint.sh"]
    expose:
      - 8383
    ports:
      - 8383:8383
    volumes:
      - type: bind
        source: ./coordinator
        target: /home/.revault_coordinatord
    depends_on:
      - coordinator_db
    build:
      context: ./docker/coordinatord
      dockerfile: Dockerfile

  bitcoind_stakeholder_1:
    image: bitcoind
    container_name: bitcoind_stakeholder_1
    entrypoint: ["./entrypoint.sh"]
    expose:
      - 9001
      - 10001
    ports:
      - 9001:9001
      - 10001:10001
    volumes:
      - type: bind
        source: ./stakeholder_1/bitcoin
        target: /root/.bitcoin
    build:
      context: ./docker/bitcoind
      dockerfile: Dockerfile
      args:
        BITCOIN_VERSION: "0.21.0"
# check https://github.com/FreekPaans/bitcoin-multi-node-regtest
